### PR TITLE
fix: support new twitter response schema

### LINKED ISSUE #397: [bug]
Your extension Blue Blocker has received a new review:

Rush Limbaugh Finally Died gave you 1 star and said:
"Blocks people who follow you. Option to avoid that doesn't work."

from Chrome Web Store

### LINKED ISSUE #406: [bug] Users aren't being collected, @undefined added to block queue
**Describe the bug**
When attempting to use Blue Blocker, it fails to collect any accounts and only fills the queue with one or multiple instances of the user `@undefined`

**To Reproduce**
1. Go to the comments section of a tweet
2. Click on the checkbox and allow user collection (I often need to reload the page when this is done, which is fine)
3. Scroll down to load blue check comments
4. See error when checking the block queue

**Expected behavior**
The queue would be filled by users with blue checks

**Screenshots and console logs**
Image

**Please fill in the following information:**
 - Browser Firefox
 - Version v0.4.16

**Additional context**
I've only gotten one or a handful of `@undefined` tags, it's not the same number of accounts that should be entering the queue

### PR DESCRIPTION
**Pull request by book000**
This pull request fixes the following issues:

- Close #397: Response to the appearance of keys indicating the relationship with the logged-in user under the `legacy` object in `relationship_perspectives` object.
- Close #406: Response to the move of target user name and screen name from legacy objects to core objects
- Support for CSRF tokens at the end of cookie strings
- Handling cases where TimelineUser type objects are passed to ParseTimelineTweet
- probably related to #402: Response to cases where UserTweets uses timeline instead of timeline_v2

### CODE REVIEW

File: src/shared.ts [hunk 1]
```diff
@@ -613,15 +619,15 @@ export async function BlockBlueVerified(user: BlueBlockerUser, config: CompiledC
...
 	const done: boolean = await (async (): Promise<boolean> => {
 		try {
 			if (
 				user?.rest_id === undefined ||
-				user?.legacy?.name === undefined ||
-				user?.legacy?.screen_name === undefined
+				getUserName(user) === undefined ||
+				getScreenName(user) === undefined
 			) {
 				throw new Error('invalid user object passed to BlockBlueVerified');
```
[the remark this answers is not in the document]
Comment (book000) [reply src/shared.ts:632]: These methods may return undefined, so we perform this verification.
(I apologise, but due to my Copilot settings, this was automatically reviewed)

File: src/global.d.ts [hunk 2]
```diff
@@ -57,12 +57,17 @@ interface BlueBlockerUser {
...
-	legacy: {
-		blocking?: boolean;
-		followed_by: boolean;
-		following: boolean;
+	core: {
+		created_at: string;
 		name: string;
 		screen_name: string;
+	};
+	legacy: {
```
Comment (rougetimelord) [inline src/global.d.ts:65]: Do these properties still exist on the 'legacy' object?

File: src/parsers/instructions.ts [hunk 3]
```diff
@@ -160,9 +171,29 @@ export function HandleInstructionsResponse(
...
+			}
+			isFailed = false;
+			break
+		} catch (err) {
+			// if we can't find the instructions, we just continue
+			_instructions = body;
+			isFailed = true;
+		}
+	}
+	if (isFailed) {
```
Comment (rougetimelord) [inline src/parsers/instructions.ts:189]: Doesn't this bypass the usual error handling?

File: src/utilities.ts
Comment (rougetimelord) [inline src/utilities.ts:1]: Not that it's super important but imo optional chaining might be better than doing undefined checks? At least for consistency across the codebase

**Review by rougetimelord — COMMENTED** [review]
Just a few comments, i like abstracting getting user details though!

File: src/global.d.ts (hunk 2 above)
Comment (book000) [reply src/global.d.ts:65]: It does not appear in the responses I can see, but I have no confirmation of this. It is possible that e.g., A/B testing is being conducted, so I chose to leave it in for backward compatibility.

Comment (rougetimelord) [reply src/global.d.ts:65]: Cool cool

File: src/parsers/instructions.ts (hunk 3 above)
Comment (book000) [reply src/parsers/instructions.ts:189]: You are correct. I will change to by sending an error exception, it will be caught by the upper layer.

File: src/utilities.ts
Comment (book000) [reply src/utilities.ts:1]: Would the following be more appropriate?

```typescript
export function getUserName(user: BlueBlockerUser) {
	const username = user?.legacy?.name || user?.core?.name;
	if (!username) {
		throw new Error(`Unable to get user name for user ${user.rest_id}`);
	}

	return username;
}
```

Comment (rougetimelord) [reply src/utilities.ts:1]: That seems good

Comment (book000) [reply src/utilities.ts:1]: ok, committed

**Comment by rougetimelord** [comment]
Can't test rn, if it works on your end it lgtm

**Comment by book000** [comment]
The following has been confirmed to work:

- Blue Verified users who are being followed are not blocked.
- Users are not displayed as undefined in the Block Queue page.
- Even if `ct0` is at the end of the cookie string, the token is obtained correctly and the blocking process works.
- There are no parsing errors when viewing user pages.

**Review by cooljeanius — APPROVED** [review]
on behalf of @rougetimelord

**Review by rougetimelord — APPROVED** [review]
